id: P66804470
initial_creation_type: input
source_metadata:
  title: Nyoshul Khenpo Jamyang Dorje
  language: es
  description: 'Texts by the great Dzogchen teacher and historian Nyoshul Khenpo Jamyang
    Dorje (smyo shul mkhan po ''jam dbyangs rdo rje, 1932–1999):'
  volume:
    51f3f2d5284248a6a8cf629ec535a0b9:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    2ab87e88bce141df9695019b373f942f:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    e8df941f622241baac2072925ae1e2e3:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Dzogchen
    6ff304539dd64599a06b885d565d6ed7:
      title: The Five Wisdoms
      parent: Dzogchen
    8a9753e94fb2444194f07433fe51b3e0:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    a90f9589d3ce4e9c8d7f9f5b7bca161a:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Poems
    ff2836b99623434d9f6c9f838a34d584:
      title: Natural Great Peace
      parent: Poems
created_at: '2022-03-01T01:05:41.716383'
last_modified_at: '2022-03-01T01:05:41.716386'
